### PR TITLE
Fixed isNaN function to add compatibility with IE

### PR DESCRIPTION
**Pull request by oxigenka**
Checked in IE 11, Edge 13, Chrome 48, Safari 9.01 & Firefox 44 - it works everywhere of these

### CODE REVIEW

**Comment by YuryStrozhevsky** [comment]
Ok, since there are no possibility to have "String" or "undefined" I do allow the fix, thanks.

**Comment by oxigenka** [comment]
There's another thing that could allow to help debugging. I've noticed that catches in promises aren't include info about the exact error has happened. If it had been done, I believe that source of this problem would have been discovered much faster

**Comment by YuryStrozhevsky** [comment]
There are no Promises in ASN1js project.

**Comment by oxigenka** [comment]
Sorry, yes, you're right, I mean promises that are in PKI.js, which uses the ASN1.js. I've used both these projects to generate the private key and CSR in the app I'm working on.

**Comment by YuryStrozhevsky** [comment]
If you have problems with error handling in PKIjs then please be more specific about code routine where it is happend.

**Pull request merged**
